--------------------------------------------------------
--  File created - Saturday-January-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence PACJENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BD2"."PACJENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRACOWNIK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BD2"."PRACOWNIK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BADANIE_SKL_Z
--------------------------------------------------------

  CREATE TABLE "BD2"."BADANIE_SKL_Z" 
   (	"ID" NUMBER(*,0), 
	"ID1" NUMBER(*,0), 
	"ID_T_B" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CENNIK
--------------------------------------------------------

  CREATE TABLE "BD2"."CENNIK" 
   (	"COST" NUMBER, 
	"FROM" DATE, 
	"To" DATE, 
	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KONSULTACJA
--------------------------------------------------------

  CREATE TABLE "BD2"."KONSULTACJA" 
   (	"ID" NUMBER(*,0), 
	"DATE" DATE, 
	"ID1" NUMBER(*,0), 
	"ID2" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LEKARZ
--------------------------------------------------------

  CREATE TABLE "BD2"."LEKARZ" 
   (	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LEK_OPIEKUJE_SIE_PAC
--------------------------------------------------------

  CREATE TABLE "BD2"."LEK_OPIEKUJE_SIE_PAC" 
   (	"ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ID1" NUMBER(*,0), 
	"ID2" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ODDZIAL
--------------------------------------------------------

  CREATE TABLE "BD2"."ODDZIAL" 
   (	"ID" NUMBER(*,0), 
	"NAZWA" VARCHAR2(50 CHAR), 
	"ILOSC_LOZEK" NUMBER(*,0), 
	"ID1" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PACJENT
--------------------------------------------------------

  CREATE TABLE "BD2"."PACJENT" 
   (	"ID" NUMBER(*,0), 
	"PESEL" NUMBER(*,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"SURNAME" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PIELEGNIARZ
--------------------------------------------------------

  CREATE TABLE "BD2"."PIELEGNIARZ" 
   (	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNIK
--------------------------------------------------------

  CREATE TABLE "BD2"."PRACOWNIK" 
   (	"ID" NUMBER(*,0), 
	"PESEL" NUMBER(*,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"SURNAME" VARCHAR2(50 CHAR), 
	"SALARY" NUMBER, 
	"ID1" NUMBER(*,0), 
	"PRACOWNIK_TYPE" VARCHAR2(23 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNIK_ADMINISTRACJI
--------------------------------------------------------

  CREATE TABLE "BD2"."PRACOWNIK_ADMINISTRACJI" 
   (	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACUJE_W
--------------------------------------------------------

  CREATE TABLE "BD2"."PRACUJE_W" 
   (	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ID" NUMBER(*,0), 
	"ID1" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTRACJA
--------------------------------------------------------

  CREATE TABLE "BD2"."REJESTRACJA" 
   (	"ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"NUMER_REJESTARCJI" NUMBER(*,0), 
	"CZY_PRZYJETY(bool)" NUMBER(*,0), 
	"ID1" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESULT_RANGE
--------------------------------------------------------

  CREATE TABLE "BD2"."RESULT_RANGE" 
   (	"RESULT_FROM" NUMBER(*,0), 
	"RESULT_TO" NUMBER(*,0), 
	"AGE" NUMBER(*,0), 
	"SEX" NUMBER(*,0), 
	"ID" NUMBER(*,0), 
	"ID_0" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SLOWNIK_ZLECENIA
--------------------------------------------------------

  CREATE TABLE "BD2"."SLOWNIK_ZLECENIA" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SL_BADANIA
--------------------------------------------------------

  CREATE TABLE "BD2"."SL_BADANIA" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SL_TESTY
--------------------------------------------------------

  CREATE TABLE "BD2"."SL_TESTY" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 CHAR), 
	"KOSZT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZLC_SKL_Z
--------------------------------------------------------

  CREATE TABLE "BD2"."ZLC_SKL_Z" 
   (	"ID_B_Z" NUMBER(*,0), 
	"ID" NUMBER(*,0), 
	"ID1" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZLECENIE
--------------------------------------------------------

  CREATE TABLE "BD2"."ZLECENIE" 
   (	"ID" NUMBER(*,0), 
	"ID1" NUMBER(*,0), 
	"DATE" DATE, 
	"COMISION_DATE" DATE, 
	"RESULT_TEXT" VARCHAR2(250 CHAR), 
	"RESULT_IMAGE" BLOB, 
	"RESULT_NUMBER" NUMBER(*,0), 
	"ID2" NUMBER(*,0), 
	"ID3" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("RESULT_IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for View LISTA_PACJENTOW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BD2"."LISTA_PACJENTOW" ("SURNAME", "NAME") AS 
  SELECT
    pacjent.surname,
    pacjent.name
FROM
    pacjent
ORDER BY
    pacjent.surname
;
--------------------------------------------------------
--  DDL for Index PIELEGNIARZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."PIELEGNIARZ_PK" ON "BD2"."PIELEGNIARZ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNIK_INDEX2
--------------------------------------------------------

  CREATE INDEX "BD2"."PRACOWNIK_INDEX2" ON "BD2"."PRACOWNIK" ("NAME", "SURNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KONSULTACJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."KONSULTACJA_PK" ON "BD2"."KONSULTACJA" ("ID", "ID1", "ID2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BADANIE_SKL_Z_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."BADANIE_SKL_Z_PK" ON "BD2"."BADANIE_SKL_Z" ("ID", "ID1", "ID_T_B") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX3
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX3" ON "BD2"."KONSULTACJA" ("ID1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX6
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX6" ON "BD2"."LEK_OPIEKUJE_SIE_PAC" ("ID1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACUJE_W_INDEX1
--------------------------------------------------------

  CREATE INDEX "BD2"."PRACUJE_W_INDEX1" ON "BD2"."PRACUJE_W" ("START_DATE", "END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZLECENIE_INDEX1
--------------------------------------------------------

  CREATE INDEX "BD2"."ZLECENIE_INDEX1" ON "BD2"."ZLECENIE" ("DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SLOWNIK_ZLECENIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."SLOWNIK_ZLECENIA_PK" ON "BD2"."SLOWNIK_ZLECENIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LEK_OPIEKUJE_SIÊ_PAC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."LEK_OPIEKUJE_SIÊ_PAC_PK" ON "BD2"."LEK_OPIEKUJE_SIE_PAC" ("ID", "ID1", "ID2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REJESTRACJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."REJESTRACJA_PK" ON "BD2"."REJESTRACJA" ("ID1", "ID", "NUMER_REJESTARCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."PRACOWNIK_PK" ON "BD2"."PRACOWNIK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX7
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX7" ON "BD2"."LEK_OPIEKUJE_SIE_PAC" ("ID2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZLC_SKL_Z_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."ZLC_SKL_Z_PK" ON "BD2"."ZLC_SKL_Z" ("ID_B_Z", "ID", "ID1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SL_TESTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."SL_TESTY_PK" ON "BD2"."SL_TESTY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX1
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX1" ON "BD2"."CENNIK" ("COST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CENNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."CENNIK_PK" ON "BD2"."CENNIK" ("ID", "FROM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNIK_ADMINISTRACJI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."PRACOWNIK_ADMINISTRACJI_PK" ON "BD2"."PRACOWNIK_ADMINISTRACJI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESULT_RANGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."RESULT_RANGE_PK" ON "BD2"."RESULT_RANGE" ("ID", "ID_0") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX4
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX4" ON "BD2"."KONSULTACJA" ("ID2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REJESTRACJA_INDEX1
--------------------------------------------------------

  CREATE INDEX "BD2"."REJESTRACJA_INDEX1" ON "BD2"."REJESTRACJA" ("START_DATE", "END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZLECENIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."ZLECENIE_PK" ON "BD2"."ZLECENIE" ("ID", "ID1", "ID2", "ID3") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNIK_INDEX1
--------------------------------------------------------

  CREATE INDEX "BD2"."PRACOWNIK_INDEX1" ON "BD2"."PRACOWNIK" ("PESEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACUJE_W_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."PRACUJE_W_PK" ON "BD2"."PRACUJE_W" ("ID1", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LEKARZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."LEKARZ_PK" ON "BD2"."LEKARZ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX2
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX2" ON "BD2"."CENNIK" ("FROM", "To") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ODDZIAL__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."ODDZIAL__IDX" ON "BD2"."ODDZIAL" ("ID1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX8
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX8" ON "BD2"."PACJENT" ("PESEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PACJENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."PACJENT_PK" ON "BD2"."PACJENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX5
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX5" ON "BD2"."LEK_OPIEKUJE_SIE_PAC" ("START_DATE", "END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX9
--------------------------------------------------------

  CREATE INDEX "BD2"."INDEX9" ON "BD2"."PACJENT" ("NAME", "SURNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SL_BADANIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."SL_BADANIA_PK" ON "BD2"."SL_BADANIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ODDZIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2"."ODDZIAL_PK" ON "BD2"."ODDZIAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_4_LEKARZ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2"."ARC_FKARC_4_LEKARZ" BEFORE
    INSERT OR UPDATE OF id ON lekarz
    FOR EACH ROW
DECLARE
    d   VARCHAR2(23);
BEGIN
    SELECT
        a.pracownik_type
    INTO
        d
    FROM
        pracownik a
    WHERE
        a.id =:new.id;

    IF
        ( d IS NULL OR d <> 'LEKARZ' )
    THEN
        raise_application_error(-20223,'FK LEKARZ_PRACOWNIK_FK in Table LEKARZ violates Arc constraint on Table PRACOWNIK - discriminator column PRACOWNIK_TYPE doesn''t have value ''LEKARZ'''
);
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "BD2"."ARC_FKARC_4_LEKARZ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_4_PIELEGNIARZ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2"."ARC_FKARC_4_PIELEGNIARZ" BEFORE
    INSERT OR UPDATE OF id ON pielegniarz
    FOR EACH ROW
DECLARE
    d   VARCHAR2(23);
BEGIN
    SELECT
        a.pracownik_type
    INTO
        d
    FROM
        pracownik a
    WHERE
        a.id =:new.id;

    IF
        ( d IS NULL OR d <> 'PIELEGNIARZ' )
    THEN
        raise_application_error(-20223,'FK PIELEGNIARZ_PRACOWNIK_FK in Table PIELEGNIARZ violates Arc constraint on Table PRACOWNIK - discriminator column PRACOWNIK_TYPE doesn''t have value ''PIELEGNIARZ'''
);
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "BD2"."ARC_FKARC_4_PIELEGNIARZ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FK_PRACOWNIK_ADMINISTRACJI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2"."ARC_FK_PRACOWNIK_ADMINISTRACJI" BEFORE
    INSERT OR UPDATE OF id ON pracownik_administracji
    FOR EACH ROW
DECLARE
    d   VARCHAR2(23);
BEGIN
    SELECT
        a.pracownik_type
    INTO
        d
    FROM
        pracownik a
    WHERE
        a.id =:new.id;

    IF
        ( d IS NULL OR d <> 'PRACOWNIK_ADMINISTRACJI' )
    THEN
        raise_application_error(-20223,'FK PA_PRACOWNIK_FK in Table PRACOWNIK_ADMINISTRACJI violates Arc constraint on Table PRACOWNIK - discriminator column PRACOWNIK_TYPE doesn''t have value ''PRACOWNIK_ADMINISTRACJI'''
);
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "BD2"."ARC_FK_PRACOWNIK_ADMINISTRACJI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PACJENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2"."PACJENT_TRG" 
BEFORE INSERT ON PACJENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PACJENT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BD2"."PACJENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRACOWNIK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2"."PRACOWNIK_TRG" 
BEFORE INSERT ON PRACOWNIK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRACOWNIK_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BD2"."PRACOWNIK_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PACJENT
--------------------------------------------------------

  ALTER TABLE "BD2"."PACJENT" ADD CONSTRAINT "PACJENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."PACJENT" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PACJENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PACJENT" MODIFY ("PESEL" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PACJENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ODDZIAL
--------------------------------------------------------

  ALTER TABLE "BD2"."ODDZIAL" ADD CONSTRAINT "ODDZIAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."ODDZIAL" MODIFY ("ID1" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ODDZIAL" MODIFY ("ILOSC_LOZEK" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ODDZIAL" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ODDZIAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESULT_RANGE
--------------------------------------------------------

  ALTER TABLE "BD2"."RESULT_RANGE" ADD CONSTRAINT "RESULT_RANGE_PK" PRIMARY KEY ("ID", "ID_0")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."RESULT_RANGE" MODIFY ("ID_0" NOT NULL ENABLE);
  ALTER TABLE "BD2"."RESULT_RANGE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BD2"."RESULT_RANGE" MODIFY ("RESULT_TO" NOT NULL ENABLE);
  ALTER TABLE "BD2"."RESULT_RANGE" MODIFY ("RESULT_FROM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PIELEGNIARZ
--------------------------------------------------------

  ALTER TABLE "BD2"."PIELEGNIARZ" ADD CONSTRAINT "PIELEGNIARZ_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."PIELEGNIARZ" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SL_TESTY
--------------------------------------------------------

  ALTER TABLE "BD2"."SL_TESTY" ADD CONSTRAINT "SL_TESTY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."SL_TESTY" MODIFY ("KOSZT" NOT NULL ENABLE);
  ALTER TABLE "BD2"."SL_TESTY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BD2"."SL_TESTY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LEKARZ
--------------------------------------------------------

  ALTER TABLE "BD2"."LEKARZ" ADD CONSTRAINT "LEKARZ_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."LEKARZ" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KONSULTACJA
--------------------------------------------------------

  ALTER TABLE "BD2"."KONSULTACJA" ADD CONSTRAINT "KONSULTACJA_PK" PRIMARY KEY ("ID", "ID1", "ID2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."KONSULTACJA" MODIFY ("ID2" NOT NULL ENABLE);
  ALTER TABLE "BD2"."KONSULTACJA" MODIFY ("ID1" NOT NULL ENABLE);
  ALTER TABLE "BD2"."KONSULTACJA" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "BD2"."KONSULTACJA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACOWNIK
--------------------------------------------------------

  ALTER TABLE "BD2"."PRACOWNIK" ADD CONSTRAINT "PRACOWNIK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."PRACOWNIK" ADD CONSTRAINT "CH_INH_PRACOWNIK" CHECK ( pracownik_type IN (
        'LEKARZ',
        'PIELEGNIARZ',
        'PRACOWNIK_ADMINISTRACJI'
    ) ) ENABLE;
  ALTER TABLE "BD2"."PRACOWNIK" MODIFY ("PRACOWNIK_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PRACOWNIK" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PRACOWNIK" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PRACOWNIK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PRACOWNIK" MODIFY ("PESEL" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PRACOWNIK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACOWNIK_ADMINISTRACJI
--------------------------------------------------------

  ALTER TABLE "BD2"."PRACOWNIK_ADMINISTRACJI" ADD CONSTRAINT "PRACOWNIK_ADMINISTRACJI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."PRACOWNIK_ADMINISTRACJI" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZLECENIE
--------------------------------------------------------

  ALTER TABLE "BD2"."ZLECENIE" ADD CONSTRAINT "ZLECENIE_PK" PRIMARY KEY ("ID", "ID1", "ID2", "ID3")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."ZLECENIE" MODIFY ("ID3" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ZLECENIE" MODIFY ("ID2" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ZLECENIE" MODIFY ("COMISION_DATE" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ZLECENIE" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ZLECENIE" MODIFY ("ID1" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ZLECENIE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SL_BADANIA
--------------------------------------------------------

  ALTER TABLE "BD2"."SL_BADANIA" ADD CONSTRAINT "SL_BADANIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."SL_BADANIA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BD2"."SL_BADANIA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SLOWNIK_ZLECENIA
--------------------------------------------------------

  ALTER TABLE "BD2"."SLOWNIK_ZLECENIA" ADD CONSTRAINT "SLOWNIK_ZLECENIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."SLOWNIK_ZLECENIA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BD2"."SLOWNIK_ZLECENIA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACUJE_W
--------------------------------------------------------

  ALTER TABLE "BD2"."PRACUJE_W" ADD CONSTRAINT "PRACUJE_W_PK" PRIMARY KEY ("ID1", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."PRACUJE_W" MODIFY ("ID1" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PRACUJE_W" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BD2"."PRACUJE_W" MODIFY ("START_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LEK_OPIEKUJE_SIE_PAC
--------------------------------------------------------

  ALTER TABLE "BD2"."LEK_OPIEKUJE_SIE_PAC" ADD CONSTRAINT "LEK_OPIEKUJE_SIÊ_PAC_PK" PRIMARY KEY ("ID", "ID1", "ID2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."LEK_OPIEKUJE_SIE_PAC" MODIFY ("ID2" NOT NULL ENABLE);
  ALTER TABLE "BD2"."LEK_OPIEKUJE_SIE_PAC" MODIFY ("ID1" NOT NULL ENABLE);
  ALTER TABLE "BD2"."LEK_OPIEKUJE_SIE_PAC" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "BD2"."LEK_OPIEKUJE_SIE_PAC" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CENNIK
--------------------------------------------------------

  ALTER TABLE "BD2"."CENNIK" ADD CONSTRAINT "CENNIK_PK" PRIMARY KEY ("ID", "FROM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."CENNIK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BD2"."CENNIK" MODIFY ("FROM" NOT NULL ENABLE);
  ALTER TABLE "BD2"."CENNIK" MODIFY ("COST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BADANIE_SKL_Z
--------------------------------------------------------

  ALTER TABLE "BD2"."BADANIE_SKL_Z" ADD CONSTRAINT "BADANIE_SKL_Z_PK" PRIMARY KEY ("ID", "ID1", "ID_T_B")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."BADANIE_SKL_Z" MODIFY ("ID_T_B" NOT NULL ENABLE);
  ALTER TABLE "BD2"."BADANIE_SKL_Z" MODIFY ("ID1" NOT NULL ENABLE);
  ALTER TABLE "BD2"."BADANIE_SKL_Z" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZLC_SKL_Z
--------------------------------------------------------

  ALTER TABLE "BD2"."ZLC_SKL_Z" ADD CONSTRAINT "ZLC_SKL_Z_PK" PRIMARY KEY ("ID_B_Z", "ID", "ID1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."ZLC_SKL_Z" MODIFY ("ID1" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ZLC_SKL_Z" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BD2"."ZLC_SKL_Z" MODIFY ("ID_B_Z" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REJESTRACJA
--------------------------------------------------------

  ALTER TABLE "BD2"."REJESTRACJA" ADD CONSTRAINT "REJESTRACJA_PK" PRIMARY KEY ("ID1", "ID", "NUMER_REJESTARCJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BD2"."REJESTRACJA" MODIFY ("ID1" NOT NULL ENABLE);
  ALTER TABLE "BD2"."REJESTRACJA" MODIFY ("CZY_PRZYJETY(bool)" NOT NULL ENABLE);
  ALTER TABLE "BD2"."REJESTRACJA" MODIFY ("NUMER_REJESTARCJI" NOT NULL ENABLE);
  ALTER TABLE "BD2"."REJESTRACJA" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "BD2"."REJESTRACJA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BADANIE_SKL_Z
--------------------------------------------------------

  ALTER TABLE "BD2"."BADANIE_SKL_Z" ADD CONSTRAINT "BADANIE_SKL_Z_SL_BADANIA_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."SL_BADANIA" ("ID") ENABLE;
  ALTER TABLE "BD2"."BADANIE_SKL_Z" ADD CONSTRAINT "BADANIE_SKL_Z_SL_TESTY_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."SL_TESTY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CENNIK
--------------------------------------------------------

  ALTER TABLE "BD2"."CENNIK" ADD CONSTRAINT "CENNIK_SL_TESTY_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."SL_TESTY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KONSULTACJA
--------------------------------------------------------

  ALTER TABLE "BD2"."KONSULTACJA" ADD CONSTRAINT "KONSULTACJA_LEKARZ_FK" FOREIGN KEY ("ID2")
	  REFERENCES "BD2"."LEKARZ" ("ID") ENABLE;
  ALTER TABLE "BD2"."KONSULTACJA" ADD CONSTRAINT "KONSULTACJA_PACJENT_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."PACJENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEKARZ
--------------------------------------------------------

  ALTER TABLE "BD2"."LEKARZ" ADD CONSTRAINT "LEKARZ_PRACOWNIK_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."PRACOWNIK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEK_OPIEKUJE_SIE_PAC
--------------------------------------------------------

  ALTER TABLE "BD2"."LEK_OPIEKUJE_SIE_PAC" ADD CONSTRAINT "LEK_OPIEKUJE_PAC_LEKARZ_FK" FOREIGN KEY ("ID2")
	  REFERENCES "BD2"."LEKARZ" ("ID") ENABLE;
  ALTER TABLE "BD2"."LEK_OPIEKUJE_SIE_PAC" ADD CONSTRAINT "LEK_OPIEKUJE_PAC_PACJENT_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."PACJENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ODDZIAL
--------------------------------------------------------

  ALTER TABLE "BD2"."ODDZIAL" ADD CONSTRAINT "ODDZIAL_LEKARZ_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."LEKARZ" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PIELEGNIARZ
--------------------------------------------------------

  ALTER TABLE "BD2"."PIELEGNIARZ" ADD CONSTRAINT "PIELEGNIARZ_PRACOWNIK_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."PRACOWNIK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNIK
--------------------------------------------------------

  ALTER TABLE "BD2"."PRACOWNIK" ADD CONSTRAINT "PRACOWNIK_PRACOWNIK_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."PRACOWNIK" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNIK_ADMINISTRACJI
--------------------------------------------------------

  ALTER TABLE "BD2"."PRACOWNIK_ADMINISTRACJI" ADD CONSTRAINT "PA_PRACOWNIK_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."PRACOWNIK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACUJE_W
--------------------------------------------------------

  ALTER TABLE "BD2"."PRACUJE_W" ADD CONSTRAINT "PRACUJE_W_ODDZIAL_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."ODDZIAL" ("ID") ENABLE;
  ALTER TABLE "BD2"."PRACUJE_W" ADD CONSTRAINT "PRACUJE_W_PRACOWNIK_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."PRACOWNIK" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REJESTRACJA
--------------------------------------------------------

  ALTER TABLE "BD2"."REJESTRACJA" ADD CONSTRAINT "REJESTRACJA_ODDZIAL_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."ODDZIAL" ("ID") ENABLE;
  ALTER TABLE "BD2"."REJESTRACJA" ADD CONSTRAINT "REJESTRACJA_PACJENT_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."PACJENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESULT_RANGE
--------------------------------------------------------

  ALTER TABLE "BD2"."RESULT_RANGE" ADD CONSTRAINT "RESULT_RANGE_SL_TESTY_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."SL_TESTY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZLC_SKL_Z
--------------------------------------------------------

  ALTER TABLE "BD2"."ZLC_SKL_Z" ADD CONSTRAINT "ZLC_SKL_Z_SLOWNIK_ZLECENIA_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."SLOWNIK_ZLECENIA" ("ID") ENABLE;
  ALTER TABLE "BD2"."ZLC_SKL_Z" ADD CONSTRAINT "ZLC_SKL_Z_SL_BADANIA_FK" FOREIGN KEY ("ID")
	  REFERENCES "BD2"."SL_BADANIA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZLECENIE
--------------------------------------------------------

  ALTER TABLE "BD2"."ZLECENIE" ADD CONSTRAINT "ZLECENIE_LEKARZ_FK" FOREIGN KEY ("ID3")
	  REFERENCES "BD2"."LEKARZ" ("ID") ENABLE;
  ALTER TABLE "BD2"."ZLECENIE" ADD CONSTRAINT "ZLECENIE_PACJENT_FK" FOREIGN KEY ("ID2")
	  REFERENCES "BD2"."PACJENT" ("ID") ENABLE;
  ALTER TABLE "BD2"."ZLECENIE" ADD CONSTRAINT "ZLECENIE_SLOWNIK_ZLECENIA_FK" FOREIGN KEY ("ID1")
	  REFERENCES "BD2"."SLOWNIK_ZLECENIA" ("ID") ENABLE;
